extends: airbnb-base
rules:
  linebreak-style: ["error", "unix"]
  indent: ["error", 2]
  no-console: "off"
  semi: ["error", "never"]
  'arrow-parens': ["error", "as-needed"]
  'no-unused-vars': ["error", { "argsIgnorePattern": "^_" }]
  '@stylistic/arrow-parens': ["error", "as-needed"]
  '@stylistic/indent': ["error", 2]
env:
  browser: true
plugins:
  - '@stylistic'